package com.moxos.uab.util.word;

import javax.xml.namespace.QName;

public class QNames {
    public static String get() {
        String html = "";
        html += "<html>";
        html += "<head>";
        html += "    <title>Title</title>";
        html += "    <style>";
        html += "        @page {";
        html += "            size: letter;";
        html += "            margin-top: 0.5in;";
        html += "            margin-left: 1in;";
        html += "            margin-top: 1in;";
        html += "            margin-bottom: 0.5in;";
        html += "            @bottom-center {";
        html += "                content: 'Página ' counter(page);";
        html += "            }";
        html += "            @top-center {";
        html += "                content: element(header);";
        html += "                padding-top: 3cm; /* Ajusta este valor según el espacio deseado en cada página */";
        html += "            }";
        html += "        }";
        html += "        .page {";
        html += "            width: 8.5in;";
        html += "            height: 11in;";
        html += "            margin: 0 auto;";
        html += "        }";
        html += "";
        html += "        body {";
        html += "            font-family: 'Arial', serif;";
        html += "            font-size: 12pt;";
        html += "            line-height: 1.5;";
        html += "            margin: 0;";
        html += "            padding: 0;";
        html += "            text-align-all: justify;";
        html += "        }";
        html += "";
        html += "        header {";
        html += "            display: block;";
        html += "            height: 1in;";
        html += "            background-color: lightgray;";
        html += "        }";
        html += "";
        html += "        table {";
        html += "            width: 90%;";
        html += "        }";
        html += "";
        html += "        .content {";
        html += "            min-height: 8in;";
        html += "            margin-top: 0.5in;";
        html += "            margin-bottom: 0.5in;";
        html += "        }";
        html += "";
        html += "        footer {";
        html += "            display: none;";
        html += "            background-color: lightgray;";
        html += "            color: black;";
        html += "            padding: 10px;";
        html += "            text-align: center;";
        html += "            font-size: 14px;";
        html += "        }";
        html += "        h1 {";
        html += "            font-size: 12pt;";
        html += "            line-height: 150%;";
        html += "            font-family: 'Arial', 'SansSerif';";
        html += "        }";
        html += "";
        html += "        li {";
        html += "            text-align: justify;";
        html += "            font-size: 12pt;";
        html += "        }";
        html += "";
        html += "        p {";
        html += "            font-family: 'Arial', serif;";
        html += "            text-indent: 0.5in;";
        html += "            font-size: 12pt;";
        html += "            margin: 0;";
        html += "            padding: 0;";
        html += "            line-height: 150%;";
        html += "            text-align: justify;";
        html += "            padding-bottom: 10px;";
        html += "        }";
        html += "";
        html += "        span {";
        html += "            font-family: 'Arial', serif;";
        html += "            text-indent: 0.5in;";
        html += "            margin: 0;";
        html += "            padding: 0;";
        html += "            line-height: 150%;";
        html += "            text-align: justify;";
        html += "            padding-bottom: 10px;";
        html += "        }";
        html += "";
        html += "        @media print {";
        html += "            .content {";
        html += "                position: running(header);";
        html += "                margin-right: 0pt;";
        html += "                margin-left: 0pt;";
        html += "            }";
        html += "            .page {";
        html += "                margin: 0 auto;";
        html += "                padding: 0;";
        html += "                page-break-after: always;";
        html += "            }";
        html += "        }";
        html += "    </style>";
        html += "</head>";
        html += "<body>";
        html += "<div class='page'>";
        html += "    <header>";
        html += "        <h2>Universidad Autonoma del Beni</h2>";
        html += "    </header>";
        html += "    <div class='content' contenteditable='true'>";
        html += "        <h1>1. IDENTIFICACIÓN DE LA ASIGNATURA</h1>";
        html += "        <div style='display: flex; justify-content: center;  align-items: center;'>";
        html += "            <table style='border: 1px solid black; width: 80%; border-collapse: collapse;'>";
        html += "                <thead>";
        html += "                <tr>";
        html += "                    <th style='border: 1px solid black; background: #D9D9D9' colspan='2'>DATOS DE LA ASIGNATURA</th>";
        html += "                </tr>";
        html += "                </thead>";
        html += "                <tbody>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Facultad";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${facultad}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Carrera";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${carrera}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Grado académico";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${gradoacademico}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Sistema";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${sistema}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Ciclo";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${ciclo}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Año o semestre";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${aniosemestre}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Área o ámbito profesional";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${areaambito}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Asignatura";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${asignatura}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Sigla de la asignatura";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${sigla}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Prerrequisito";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${preresquisito}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Clasificación de la asignatura según el plan de estudio";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${clasificacion}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Horas Teórica/Semana";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${horasteorica}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Horas Practicas/Semana";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${horaspracticas}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Total, Hora Académica/Semana";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${totalhoraacademica}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Total, Hora Académica Semestre o Año";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${totalhoraacademicasemestre}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Turno";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${turno}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Gestión Académica";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${gestionacademica}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td colspan='2'";
        html += "                        style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold; text-align: center'>";
        html += "                        DATOS DEL DOCENTE";
        html += "                    </td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Nombres y Apellido:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${nombredocente}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Categoría y Tiempo de Dedicación:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${categoriadocente}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Modalidad de Ingreso:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${modalidaddeingreso}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Teléfono:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${telefono}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Correo electrónico:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'>${correoelectronico}</td>";
        html += "                </tr>";
        html += "                <tr>";
        html += "                    <td style='border: 1px solid black; background: #D9D9D9; padding: 5px; width: 50%; font-family: Arial, SansSerif; font-size: 12pt; font-weight: bold'>";
        html += "                        Exigencia del Docente que imparte la asignatura:";
        html += "                    </td>";
        html += "                    <td style='border: 1px solid black; background: #FFFFFF; padding: 5px; width: 50%;'></td>";
        html += "                </tr>";
        html += "                </tbody>";
        html += "            </table>";
        html += "        </div>";
        html += "        <h1>2. MARCO REFERENCIAL</h1>";
        html += "        ${marcoreferencial}";
        html += "        <h1>3. JUSTIFICACIÓN</h1>";
        html += "        ${justificaciones}";
        html += "        <h1>4. PROPÓSITOS</h1>";
        html += "        ${propositos}";
        html += "        <h1>5. SISTEMA DE OBJETIVOS</h1>";
        html += "        <h1>5.1 OBJETIVO GENERAL DE LA ASIGNATURA</h1>";
        html += "        ${sistemasobeticosgeneral}";
        html += "        <h1>5.2 OBJETIVO EDUCATIVO</h1>";
        html += "        ${sistemasobeticoseducativo}";
        html += "        <h1>5.3 OBJETIVOS INSTRUCTIVOS</h1>";
        html += "        ${sistemasobeticosinstructivo}";
        html += "        <h1>6. CONTENIDOS</h1>";
        html += "        ${contenidosanaliticos}";
        html += "        <h1>7. MODALIDAD Y METODOLOGÍA A UTILIZAR EN EL PEA</h1>";
        html += "        ${metodologia}";
        html += "        <h1>8. FORMAS DE ORGANIZACIÓN</h1>";
        html += "        ${formasdeorganizacion}";
        html += "        <h1>9. RECURSOS EDUCATIVOS Y TECNOLÓGICOS</h1>";
        html += "        ${recursoseducativos}";
        html += "        <h1>10. SISTEMA DE EVALUACIÓN</h1>";
        html += "        <h1>1. COMPONENTES DEL SISTEMA DE EVALUACIÓN</h1>";
        html += "        ${sistemasevaluacion}";
        html += "        <h1>2. CRITERIOS DE EVALUACIÓN (REQUISITOS MÍNIMOS DE APROBACIÓN)</h1>";
        html += "        ${sistemasevaluacioncriterio}";
        html += "        <h1>11. BIBLIOGRAFÍA</h1>";
        html += "        ${bibiliografia}";
        html += "        <h1>12. CRONOGRAMA DE ACTIVIDADES</h1>";
        html += "        ${cronogra}";
        html += "    </div>";
        html += "    <footer>";
        html += "    </footer>";
        html += "</div>";
        html += "</body>";
        html += "</html>";
        return html;
    }
}